# local deste arquivo: ./docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8
    env_file:
      - ./.db.env
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sge_api_network
    restart: always

  sge_api:
    build: ./sge_api
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - sge_api_network
    # restart: always


  sge_app:
    build: ./sge_app
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - sge_app_network
      - sge_api_network
    restart: always


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.phpmyadmin.env
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - sge_api_network
    restart: always


volumes:
  mysql_data:
    external: true

networks:
  sge_app_network:
  sge_api_network: